# .readthedocs.yaml - https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"

conda:
  environment: docs/.rtd-environment.yml

formats:
  - htmlzip
  - pdf
